region: us-west-2
env_name: prod
deployment_id: core-uswest2
tags:
  region: us-west-2
  env_name: prod
  deployment_id: core-uswest2
private_connect_role_name: us-west-2-private-connect

# Control Plane Infra - Start
api_authorization: CUSTOM
api_authorizer_gdot_url: https://cloudatlas.salesforce.com/services/c2c/api/v1/validateJwt
api_authorizer_c2c_key_secret_name: C2C-EC-Keys-Prod
api_access_whitelist_ips:
  # Monitoring VM
  - 44.228.157.29/32

lambda_memory_size: 2048
# Control Plane Infra - End

# Dataplane Inbound - Start
inbound_vpc_cidr: 10.0.0.0/22
inbound_data_plane_node_group_instance_types:
  - m5.4xlarge
inbound_data_plane_node_group_max_size: 6
# Dataplane Inbound - End

# Dataplane Outbound - Start
outbound_data_plane_node_group_instance_types:
  - m5.4xlarge
outbound_data_plane_node_group_max_size: 6
outbound_vpcs_config:
  1:
    vpc_cidr: 10.0.16.0/20
# Dataplane Outbound - End

# Payload - Start
lambda_layer_s3_key: zip/cni_common_v274.zip
lambda_function_s3_key: zip/api_v4.zip

metrics_exporter:
  image: 325178561262.dkr.ecr.us-west-2.amazonaws.com/cni-metrics-exporter
  version: '9'
monitoring:
  image: 325178561262.dkr.ecr.us-west-2.amazonaws.com/cni-monitoring
  version: '4'
dataplane_inbound:
  image: 325178561262.dkr.ecr.us-west-2.amazonaws.com/cni-nginx-proxy-inbound
  version: '20'
dataplane_outbound:
  image: 325178561262.dkr.ecr.us-west-2.amazonaws.com/cni-nginx-proxy-outbound
  version: '20'
# Payload - End
enable_sitebridge: true
sitebridge_config:
  bgp_asn: 64902
  control_plane_ips:
    - 192.168.101.143/32
    - 192.168.101.172/32
    - 192.168.101.210/32
  data_plane_cidrs:
    - 100.112.0.0/16
    - 100.112.0.0/16
    - 100.112.0.0/16
  gateway_ips:
    - 44.233.119.0/32
    - 44.233.119.1/32
    - 44.233.119.10/32
  forwarded_domains:
    - my.salesforce.com
    - sfdc.net
    - force.com

# K8S Config - Start
eks_k8s_version: '1.15'
# K8S Config - End

